/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: motorCmd.idl
  Source: motorCmd.hpp
  Cyclone DDS: v0.10.5

*****************************************************************/
#ifndef DDSCXX_MOTORCMD_HPP
#define DDSCXX_MOTORCMD_HPP

#include <array>

namespace ROBOT
{
class MotorCmd
{
private:
 std::array<float, 18> q_ = { };
 std::array<float, 18> kp_ = { };
 std::array<float, 18> tau_ = { };

public:
  MotorCmd() = default;

  explicit MotorCmd(
    const std::array<float, 18>& q,
    const std::array<float, 18>& kp,
    const std::array<float, 18>& tau) :
    q_(q),
    kp_(kp),
    tau_(tau) { }

  const std::array<float, 18>& q() const { return this->q_; }
  std::array<float, 18>& q() { return this->q_; }
  void q(const std::array<float, 18>& _val_) { this->q_ = _val_; }
  void q(std::array<float, 18>&& _val_) { this->q_ = _val_; }
  const std::array<float, 18>& kp() const { return this->kp_; }
  std::array<float, 18>& kp() { return this->kp_; }
  void kp(const std::array<float, 18>& _val_) { this->kp_ = _val_; }
  void kp(std::array<float, 18>&& _val_) { this->kp_ = _val_; }
  const std::array<float, 18>& tau() const { return this->tau_; }
  std::array<float, 18>& tau() { return this->tau_; }
  void tau(const std::array<float, 18>& _val_) { this->tau_ = _val_; }
  void tau(std::array<float, 18>&& _val_) { this->tau_ = _val_; }

  bool operator==(const MotorCmd& _other) const
  {
    (void) _other;
    return q_ == _other.q_ &&
      kp_ == _other.kp_ &&
      tau_ == _other.tau_;
  }

  bool operator!=(const MotorCmd& _other) const
  {
    return !(*this == _other);
  }

};

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::ROBOT::MotorCmd>::getTypeName()
{
  return "ROBOT::MotorCmd";
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::ROBOT::MotorCmd>::type_map_blob_sz() { return 342; }
template<> constexpr unsigned int TopicTraits<::ROBOT::MotorCmd>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::ROBOT::MotorCmd>::type_map_blob() {
  static const uint8_t blob[] = {
 0x7e,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x85,  0xa7,  0x44,  0x71,  0xcc,  0x74,  0x06, 
 0x7d,  0xbd,  0xee,  0xca,  0xd3,  0xab,  0x79,  0x00,  0x66,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x56,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00, 
 0x16,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x31,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x12,  0x09,  0x76,  0x94,  0xf4,  0xa6,  0x00,  0x00,  0x16,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x12,  0x09,  0x26,  0xb5,  0x68,  0xe4,  0x00,  0x00,  0x16,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x12,  0x09,  0x45,  0x80, 
 0xc2,  0x74,  0x00,  0x00,  0xa6,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x37,  0x8b,  0x54, 
 0x4b,  0xcc,  0x4a,  0xd1,  0x71,  0xfe,  0x57,  0x4e,  0xba,  0x7e,  0x41,  0x00,  0x8e,  0x00,  0x00,  0x00, 
 0xf2,  0x51,  0x01,  0x00,  0x18,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x10,  0x00,  0x00,  0x00, 
 0x52,  0x4f,  0x42,  0x4f,  0x54,  0x3a,  0x3a,  0x4d,  0x6f,  0x74,  0x6f,  0x72,  0x43,  0x6d,  0x64,  0x00, 
 0x6a,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x1c,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x31,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x12,  0x09,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0x71,  0x00,  0x00,  0x00,  0x1d,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x12,  0x09,  0x00,  0x00, 
 0x03,  0x00,  0x00,  0x00,  0x6b,  0x70,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x1e,  0x00,  0x00,  0x00, 
 0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x12,  0x09,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x74,  0x61,  0x75,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x37,  0x8b,  0x54,  0x4b,  0xcc,  0x4a,  0xd1, 
 0x71,  0xfe,  0x57,  0x4e,  0xba,  0x7e,  0x41,  0xf1,  0x85,  0xa7,  0x44,  0x71,  0xcc,  0x74,  0x06,  0x7d, 
 0xbd,  0xee,  0xca,  0xd3,  0xab,  0x79, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::ROBOT::MotorCmd>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x85,  0xa7,  0x44,  0x71,  0xcc,  0x74,  0x06,  0x7d,  0xbd,  0xee,  0xca, 
 0xd3,  0xab,  0x79,  0x00,  0x6a,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x37,  0x8b,  0x54,  0x4b,  0xcc,  0x4a,  0xd1,  0x71,  0xfe,  0x57,  0x4e, 
 0xba,  0x7e,  0x41,  0x00,  0x92,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::ROBOT::MotorCmd>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::ROBOT::MotorCmd>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::ROBOT::MotorCmd)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::ROBOT::MotorCmd>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::ROBOT::MotorCmd& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!write(streamer, instance.q()[0], instance.q().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!write(streamer, instance.kp()[0], instance.kp().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!write(streamer, instance.tau()[0], instance.tau().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::ROBOT::MotorCmd& instance, bool as_key) {
  auto &props = get_type_props<::ROBOT::MotorCmd>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::ROBOT::MotorCmd& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!read(streamer, instance.q()[0], instance.q().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!read(streamer, instance.kp()[0], instance.kp().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!read(streamer, instance.tau()[0], instance.tau().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::ROBOT::MotorCmd& instance, bool as_key) {
  auto &props = get_type_props<::ROBOT::MotorCmd>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::ROBOT::MotorCmd& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!move(streamer, instance.q()[0], instance.q().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!move(streamer, instance.kp()[0], instance.kp().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!move(streamer, instance.tau()[0], instance.tau().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::ROBOT::MotorCmd& instance, bool as_key) {
  auto &props = get_type_props<::ROBOT::MotorCmd>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::ROBOT::MotorCmd& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!max(streamer, instance.q()[0], instance.q().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!max(streamer, instance.kp()[0], instance.kp().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!max(streamer, instance.tau()[0], instance.tau().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::ROBOT::MotorCmd& instance, bool as_key) {
  auto &props = get_type_props<::ROBOT::MotorCmd>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_MOTORCMD_HPP
